# Generated by Django 5.2.17 on 2026-09-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_frota', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('status_inventario', models.CharField(choices=[('PENDENTE', 'Pendente'), ('INVENTARIADA', 'Inventariada')], default='PENDENTE', max_length=12)),
                ('data_inventario', models.DateTimeField(blank=True, null=True)),
                ('perfil_inventariado_por', models.CharField(blank=True, max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'frota',
                'verbose_name_plural': 'frotas',
                'ordering': ['numero_frota'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('frota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='inventario.frota')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['nome', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_frota', models.CharField(max_length=50)),
                ('perfil', models.CharField(max_length=10)),
                ('acao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('frota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='inventario.frota')),
            ],
            options={
                'verbose_name': 'registro de histórico',
                'verbose_name_plural': 'históricos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
